### ISSUE TITLE
Syntax error in init.sh on Ubuntu 16.10

### ISSUE THREAD

**Issue by ezio-melotti** [python/docker-bpo#5]
I tried to rebuild the image with Ubuntu 16.10, and when I run `docker start` I got the error:
`/init.sh: 7: /init.sh: Syntax error: "(" unexpected (expecting "fi")`

I removed the `function`s from [init.sh](https://github.com/python/docker-bpo/blob/master/image/init.sh#L7)  (i.e. `stop_all() {...}`) and I was able to rebuild and start the container, however I noticed that those were added in ed0498a for Fedora.

If this doesn't work on Fedora without the `function`, is there a way to make it work or should we just remove fedora support (why do we even have it?)?  FWIW I also tried the syntax `function stop_all {...}` (without `()`) but it doesn't work.  Replacing the shebang with `/bin/bash` might fix the problem for both, but I haven't tried.

**Comment by soltysh** [comment]
I'll leave this open until I'll open a followup I've mentioned in https://github.com/python/docker-bpo/pull/6#issuecomment-285594739

**Comment by zware** [comment]
`init.sh` has changed significantly in the past 5 years, and this seems to be no longer relevant.
